### ISSUE TITLE
Duplication of effort

### ISSUE THREAD

**Issue by csgillespie** [r-community/tweet-explorer#3]
The list of twitter accounts seems to duplicate effort.

A list of [groups](https://github.com/jumpingrivers/meetingsR) and a corresponding [CSV file](https://github.com/jumpingrivers/meetingsR/blob/gh-pages/groups.csv) is available. Extracting twitter tags should be easy.

Keeping one list up to date is hard. Two lists is impossible ;)

**Comment by benubah** [comment]
Thanks! @csgillespie  You have a great point! I would get some Twitter accounts from your list. I guess we could also announce for groups to update their Twitter columns on your list. Could you post/tweet on this as soon as possible? I can also retweet it and emphasize on it. But this list is focused on user-groups only.

My list is a little different - it is not just user-groups. If you look at the [list](https://github.com/r-community/tweet-explorer/blob/master/twitter_account.csv), it is just Twitter account names of **R User groups**, **R organizations**, **R service providers**, **projects**, **educational programs**, and even **events** that have a Twitter account. Would it be desirable to have things like @tidyversetweets, @rstudiotips, @R_Forwards added to your current list of groups? My humble guess is that, this is not the desired goal. What do you think?

**Comment by benubah** [comment]
Hi @csgillespie You can announce here: https://community.rstudio.com/t/global-r-twitter-community/69862 or on the r-user-group slack.
I can also do the announce there if you want me to....

And we could keep adding reminders this whole week to gain traction.

Thanks!

**Comment by csgillespie** [comment]
Hi @benubah. Anything that involves asking people to update two lists seems __wrong__ to me. Ditto for manually copying one list to another.

---

> R User groups, R organizations, R service providers, projects, educational programs, and even events

The list currently has useR groups & events.

**Comment by benubah** [comment]
Thanks @csgillespie  for your ideas....

The truth is that I don't even have the time to manually copy from one list to another
that's why I announced to the public.

Because of time, I hurriedly used `rtweet` package to do 

   `search_users("RLadies", n=1000)`

And it returned 200+ related RLadies Twitter accounts.

I have some volunteers who are trying to gather data around the Web. Maybe they could look at your list in the future.

I will ask if they have time to help.

I just suddenly needed Twitter accounts focused on `#rstats` to gather data for a slide in a presentation.

Cheers
